#!/usr/bin/env python3
"""OMR worker for Piano Helper.

Always-on poller that turns uploaded sheet music into MusicXML. It runs on an
Oracle Cloud Always Free ARM VM (see README.md) and is the compute backend that
replaced the old GitHub Actions runner. The transport contract with the
Cloudflare Pages Functions is unchanged and lives entirely in R2:

  input   uploads/<jobId>              raw PDF/PNG/JPEG bytes (any content-type)
  output  results/<jobId>.musicxml     UTF-8 MusicXML

Loop, for each object under uploads/:
  1. validate the jobId (it is a UUID; reject anything else),
  2. skip if results/<jobId>.musicxml already exists (idempotent re-runs),
  3. download the upload, rasterize all PDF pages with pdftoppm if needed and
     stitch them into one tall PNG,
  4. run oemer (deskew disabled on the PDF path), fall back to homr, and on
     success upload the MusicXML,
  5. if BOTH engines fail, upload a failure-sentinel MusicXML the browser
     detects (functions ... src/omr.ts FAILURE_SENTINEL_RE),
  6. delete uploads/<jobId> so it is not reprocessed.

Per-job exceptions are caught so one bad upload never kills the loop.

Config comes from env vars (no secrets in the file, none on disk):
  R2_S3_ENDPOINT        https://<account>.r2.cloudflarestorage.com
  R2_ACCESS_KEY_ID      R2 S3 API token access key id
  R2_SECRET_ACCESS_KEY  R2 S3 API token secret
  R2_BUCKET             bucket name (piano-helper-omr)
  OMR_POLL_SECONDS      poll interval, optional (default 5)
"""

import os
import subprocess
import sys
import tempfile
import time
import uuid

import boto3
from botocore.client import Config
from botocore.exceptions import ClientError

UPLOAD_PREFIX = "uploads/"
RESULT_SUFFIX = ".musicxml"
RESULT_CONTENT_TYPE = "application/vnd.recordare.musicxml+xml"
DEFAULT_POLL_SECONDS = 5

# Rasterization DPI for the PDF path. oemer exposes no DPI/quality knob of its own
# (its CLI is just -o, --use-tf, --save-cache, -d/--without-deskew), so the raster we
# hand it is the ONLY preprocessing lever we own. 400 (up from the old 300) gives the
# ML engine denser staff-line and notehead pixels, which is the highest-leverage,
# lowest-risk free fidelity gain (#109). It is deliberately conservative versus 600 to
# stay within the Oracle Always Free ARM VM's memory/time budget: a single A4 page at
# 400 DPI is ~3300x4675 px (~46 MP), and we may stitch several pages into one tall
# image below, so the working bitmap stays bounded. Bump cautiously if the VM allows.
PDF_RASTER_DPI = 400

# Resource guards for the stitched raster. The upload Function caps inputs at 10 MB
# (src/omr-server.ts MAX_UPLOAD_BYTES), but a sparse VECTOR PDF compresses so well that
# 10 MB can still hold hundreds of pages. At 400 DPI each A4 page is ~15.5 MP, so an
# unbounded vertical stitch of a crafted many-page PDF would allocate a multi-GB RGB
# bitmap on a box that also runs the oemer PyTorch/onnx stack: a real OOM that would
# kill the always-on poller (the OS OOM-killer is not catchable by poll_once). Bound BOTH
# the page count and the total stitched pixel area; exceeding either raises RuntimeError,
# which poll_once turns into a clean failure sentinel instead of crashing the worker.
# 60 pages * 15.5 MP ~= 930 MP is also the ceiling we hand oemer (well past any real score).
MAX_STITCH_PAGES = 60
MAX_STITCH_PIXELS = 1_000_000_000  # ~1 GP; RGB canvas ~3 GB worst case, then freed.

# Byte-compatible with src/omr.ts FAILURE_SENTINEL_RE = /name="omr-status"\s*>\s*failed/.
# Written to the result key when both engines fail so the browser stops polling and
# shows a friendly error instead of rendering a near-empty score as success.
FAILURE_SENTINEL = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
  <work><work-title>OMR failed</work-title></work>
  <identification>
    <miscellaneous>
      <miscellaneous-field name="omr-status">failed</miscellaneous-field>
    </miscellaneous>
  </identification>
  <part-list>
    <score-part id="P1"><part-name>Music</part-name></score-part>
  </part-list>
  <part id="P1">
    <measure number="1">
      <attributes>
        <divisions>1</divisions>
        <key><fifths>0</fifths></key>
        <time><beats>4</beats><beat-type>4</beat-type></time>
        <clef><sign>G</sign><line>2</line></clef>
      </attributes>
      <note><rest/><duration>4</duration><type>whole</type></note>
    </measure>
  </part>
</score-partwise>
""".encode("utf-8")


def log(message):
    """Timestamped line on stdout so journald captures it under the unit."""
    print(time.strftime("%Y-%m-%dT%H:%M:%S"), message, flush=True)


def require_env(name):
    value = os.environ.get(name)
    if not value:
        log("FATAL missing required env var %s" % name)
        sys.exit(1)
    return value


def is_uuid(value):
    """The jobId is a UUID generated by the Pages Function. Validate before it ever
    reaches an S3 key or a filesystem path."""
    try:
        return str(uuid.UUID(value)) == value.lower()
    except (ValueError, AttributeError, TypeError):
        return False


def make_client():
    endpoint = require_env("R2_S3_ENDPOINT")
    access_key = require_env("R2_ACCESS_KEY_ID")
    secret_key = require_env("R2_SECRET_ACCESS_KEY")
    return boto3.client(
        "s3",
        endpoint_url=endpoint,
        aws_access_key_id=access_key,
        aws_secret_access_key=secret_key,
        # R2 ignores region but boto3 requires one; "auto" matches the old workflow.
        region_name="auto",
        config=Config(signature_version="s3v4"),
    )


def list_upload_job_ids(client, bucket):
    """Yield valid jobIds for every object under uploads/. Paginated so a backlog
    larger than 1000 keys is handled."""
    paginator = client.get_paginator("list_objects_v2")
    for page in paginator.paginate(Bucket=bucket, Prefix=UPLOAD_PREFIX):
        for obj in page.get("Contents", []):
            key = obj["Key"]
            if not key.startswith(UPLOAD_PREFIX):
                continue
            job_id = key[len(UPLOAD_PREFIX):]
            if not job_id:
                continue
            if not is_uuid(job_id):
                log("skip non-uuid upload key %r" % key)
                continue
            yield job_id


def result_exists(client, bucket, job_id):
    try:
        client.head_object(Bucket=bucket, Key=result_key(job_id))
        return True
    except ClientError as err:
        code = err.response.get("Error", {}).get("Code")
        if code in ("404", "NoSuchKey", "NotFound"):
            return False
        raise


def upload_key(job_id):
    return UPLOAD_PREFIX + job_id


def result_key(job_id):
    return "results/" + job_id + RESULT_SUFFIX


def sniff_mime(input_path):
    """Return the libmagic mime-type string for the input, or "" on failure."""
    return subprocess.run(
        ["file", "--brief", "--mime-type", input_path],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()


def rasterize_if_pdf(input_path, workdir):
    """oemer needs a single raster image. Sniff the type and, for a PDF, render EVERY
    page to PNG with poppler's pdftoppm at PDF_RASTER_DPI, then stitch all pages
    vertically into one tall PNG so no music past page 1 is dropped (the old code
    rendered only the first page).

    Returns (image_path, is_pdf). is_pdf lets the caller disable oemer's deskew on the
    clean vector-PDF path (a vector raster is already orthogonal; deskew can warp it)."""
    kind = sniff_mime(input_path)
    log("detected mime %r" % kind)

    if kind == "application/pdf":
        out_prefix = os.path.join(workdir, "page")
        # No -f/-l: render ALL pages. -r sets the DPI (the only quality lever we own).
        subprocess.run(
            ["pdftoppm", "-png", "-r", str(PDF_RASTER_DPI), input_path, out_prefix],
            check=True,
        )
        # pdftoppm appends -1, -01, or -001 depending on page-count width; sorting the
        # zero-padded names keeps pages in document order (page-001 < page-002 < ...).
        pages = sorted(
            os.path.join(workdir, p)
            for p in os.listdir(workdir)
            if p.startswith("page-") and p.endswith(".png")
        )
        if not pages:
            raise RuntimeError("pdftoppm produced no page image")
        log("rasterized %d page(s) at %d DPI" % (len(pages), PDF_RASTER_DPI))
        stitched = os.path.join(workdir, "stitched.png")
        return stitch_pages_vertical(pages, stitched), True

    if kind == "image/png":
        return _rename_to(input_path, os.path.join(workdir, "page.png")), False

    if kind == "image/jpeg":
        return _rename_to(input_path, os.path.join(workdir, "page.jpg")), False

    # Best effort: hand the raw bytes to oemer as a PNG and let it try.
    log("unrecognized mime %r; treating as PNG" % kind)
    return _rename_to(input_path, os.path.join(workdir, "page.png")), False


def stitch_pages_vertical(page_paths, dest_path):
    """Stack page PNGs top-to-bottom into one tall PNG and write it to dest_path.

    oemer reads ONE image, so a multi-page PDF must collapse to a single raster.
    Vertical stitching (rather than picking one "best" page) preserves ALL music: a
    grand staff reads the same whether the systems sit on one page or several, and the
    engine processes staves top-to-bottom regardless. A single page short-circuits to a
    plain copy (no compositing cost). Canvas width is the widest page so nothing is
    cropped; narrower pages are left-aligned on a white background (matches sheet-music
    paper and the engine's binarization assumptions). Returns dest_path.

    Pillow is already an oemer runtime dependency (see requirements.txt), so this adds
    no new dependency. Imported lazily so the rest of the module (and its unit tests)
    stays importable on a host without Pillow installed.

    Resource-safety: a crafted many-page 10 MB vector PDF could otherwise stitch into a
    multi-GB bitmap and OOM-kill the worker, so reject more than MAX_STITCH_PAGES pages
    and any total area over MAX_STITCH_PIXELS before allocating the canvas. Pillow's
    decompression-bomb guard is also armed (MAX_IMAGE_PIXELS) so a single crafted page
    cannot bomb-decode on Image.open."""
    if not page_paths:
        raise RuntimeError("no pages to stitch")
    if len(page_paths) > MAX_STITCH_PAGES:
        raise RuntimeError(
            "too many pages to stitch: %d > %d" % (len(page_paths), MAX_STITCH_PAGES)
        )

    from PIL import Image

    # Arm Pillow's decompression-bomb guard so an Image.open of a crafted page raises
    # rather than silently decoding a giant bitmap. MAX_STITCH_PIXELS comfortably exceeds
    # one real 400 DPI A4 page (~15.5 MP), so legitimate pages are unaffected.
    Image.MAX_IMAGE_PIXELS = MAX_STITCH_PIXELS

    if len(page_paths) == 1:
        # Single page: just normalize to RGB at dest_path, no compositing.
        with Image.open(page_paths[0]) as only:
            only.convert("RGB").save(dest_path)
        return dest_path

    images = []
    try:
        for path in page_paths:
            images.append(Image.open(path).convert("RGB"))
        total_width = max(img.width for img in images)
        total_height = sum(img.height for img in images)
        # Reject before allocating: the canvas alone would be total_width*total_height*3
        # bytes of RAM, so cap the area to keep the worker inside the VM's budget.
        if total_width * total_height > MAX_STITCH_PIXELS:
            raise RuntimeError(
                "stitched image too large: %d px > %d"
                % (total_width * total_height, MAX_STITCH_PIXELS)
            )
        canvas = Image.new("RGB", (total_width, total_height), (255, 255, 255))
        y = 0
        for img in images:
            canvas.paste(img, (0, y))
            y += img.height
        canvas.save(dest_path)
    finally:
        for img in images:
            img.close()
    return dest_path


def _rename_to(src, dest):
    """Give the input a sensible extension so oemer reads it as the right format.
    Returns the path oemer should use."""
    if src == dest:
        return src
    os.replace(src, dest)
    return dest


def find_musicxml(*dirs):
    """Return the first .musicxml/.xml file found across the given dirs, or None.
    oemer and homr differ on output path/name across versions."""
    for d in dirs:
        if not d or not os.path.isdir(d):
            continue
        for name in sorted(os.listdir(d)):
            if name.endswith(".musicxml") or name.endswith(".xml"):
                return os.path.join(d, name)
    return None


def oemer_command(image_path, out_dir, without_deskew):
    """Build the oemer argv. Pure so the deskew gating is unit-testable without running
    the engine. --without-deskew is added ONLY when without_deskew is true (the clean
    vector-PDF path): a vector raster is already orthogonal, so oemer's deskew step can
    only warp it. A scanned/photo PNG/JPEG keeps deskew on (it may be skewed)."""
    cmd = ["oemer", image_path, "-o", out_dir]
    if without_deskew:
        cmd.append("--without-deskew")
    return cmd


def run_oemer(image_path, workdir, without_deskew=False):
    """Run the primary engine. Returns the MusicXML path or None on failure."""
    out_dir = os.path.join(workdir, "oemer-out")
    os.makedirs(out_dir, exist_ok=True)
    try:
        subprocess.run(
            oemer_command(image_path, out_dir, without_deskew),
            check=True,
            cwd=workdir,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as err:
        log("oemer failed: %s" % err)
        return None
    return find_musicxml(out_dir, workdir)


def run_homr(image_path, workdir):
    """Run the fallback engine. Returns the MusicXML path or None on failure."""
    try:
        subprocess.run(["homr", image_path], check=True, cwd=workdir)
    except (subprocess.CalledProcessError, FileNotFoundError) as err:
        log("homr failed: %s" % err)
        return None
    return find_musicxml(workdir)


def process_job(client, bucket, job_id):
    """Convert one upload. Always leaves exactly one object at the result key
    (real score or sentinel) and deletes the upload so it is not reprocessed."""
    if result_exists(client, bucket, job_id):
        log("result already present for %s; deleting stale upload" % job_id)
        client.delete_object(Bucket=bucket, Key=upload_key(job_id))
        return

    with tempfile.TemporaryDirectory(prefix="omr-") as workdir:
        input_path = os.path.join(workdir, "input.bin")
        client.download_file(bucket, upload_key(job_id), input_path)

        image_path, is_pdf = rasterize_if_pdf(input_path, workdir)
        # Disable deskew only on the vector-PDF raster (already orthogonal).
        result_path = run_oemer(image_path, workdir, without_deskew=is_pdf)
        if result_path is None:
            log("oemer produced nothing for %s; trying homr" % job_id)
            result_path = run_homr(image_path, workdir)

        if result_path is not None:
            with open(result_path, "rb") as fh:
                body = fh.read()
            log("%s recognized via engine output %s" % (job_id, result_path))
        else:
            body = FAILURE_SENTINEL
            log("both engines failed for %s; writing failure sentinel" % job_id)

        client.put_object(
            Bucket=bucket,
            Key=result_key(job_id),
            Body=body,
            ContentType=RESULT_CONTENT_TYPE,
        )

    # Only delete the upload after the result is durably written.
    client.delete_object(Bucket=bucket, Key=upload_key(job_id))
    log("done %s; upload deleted" % job_id)


def poll_once(client, bucket):
    for job_id in list_upload_job_ids(client, bucket):
        try:
            process_job(client, bucket, job_id)
        except Exception as err:  # one bad upload must never kill the loop
            log("ERROR processing %s: %r" % (job_id, err))


def main():
    bucket = require_env("R2_BUCKET")
    try:
        interval = float(os.environ.get("OMR_POLL_SECONDS", DEFAULT_POLL_SECONDS))
    except ValueError:
        interval = DEFAULT_POLL_SECONDS
    if interval <= 0:
        interval = DEFAULT_POLL_SECONDS

    client = make_client()
    log("OMR worker started; bucket=%s interval=%ss" % (bucket, interval))

    while True:
        try:
            poll_once(client, bucket)
        except Exception as err:  # list/credentials hiccup: log and keep going
            log("ERROR poll cycle: %r" % err)
        time.sleep(interval)


if __name__ == "__main__":
    main()
